<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <RootNamespace>Sio.EditorSupport</RootNamespace>
    <AssemblyName>sio-langserver</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sio.Assembler\Sio.Assembler.csproj" />
    <ProjectReference Include="..\Sio.Simulator\Sio.Simulator.csproj" />
  </ItemGroup>
</Project>
