"""Emit extracted traces as a test definition in the project YAML format.

Output uses formatVersion 2.0 with `saveFile:` (community solutions are
multi-chip boards, not single .asm programs) and binds streams to puzzle
terminals via `level.<terminal-name>` targets — see docs/test-format.md.
"""

import os


def _rel(target, out_path):
    return os.path.relpath(target, os.path.dirname(out_path)).replace(os.sep, "/")


def emit_yaml(level, screenshot, config_path, save_file, traces, n_units, out_path):
    case_name = f"{level} — {os.path.splitext(os.path.basename(screenshot))[0]} (sampled run)"
    lines = [
        "# GENERATED by tools/pixel-extractor — do not hand-edit values.",
        f"# source: {screenshot}",
        f"# mapping: {config_path}",
        'formatVersion: "2.0"',
        "reviewStatus: unreviewed",
        "cases:",
        f'  - name: "{case_name}"',
        f"    saveFile: {_rel(save_file, out_path)}",
        f"    cycleLimit: {n_units}",
    ]

    inputs = [t for t in traces if t["direction"] == "input" and t["values"] is not None]
    outputs = [t for t in traces if t["direction"] == "output" and t["values"] is not None]

    if inputs:
        lines.append("    inputs:")
        for t in inputs:
            lines.append(f'      - target: "level.{t["name"]}"')
            lines.append(f'        id: "{t["name"]}"')
            lines.append(f'        samples: [{", ".join(str(v) for v in t["values"])}]')
    else:
        lines.append("    inputs: []")

    lines.append("    expectedOutputs:")
    for t in outputs:
        lines.append(f'      - source: "level.{t["name"]}"')
        lines.append(f'        streamId: "{t["name"]}"')
        lines.append('        mode: "cycle-exact"')
        lines.append("        events:")
        prev = None
        for cycle, value in enumerate(t["values"]):
            if value != prev:
                lines.append(f"          - cycle: {cycle}")
                lines.append(f"            value: {value}")
                prev = value
    lines.append("")
    return "\n".join(lines)
